# here add all instructions to run you app in production!!!
services:
  api:
    build:
      context: .
      target: production
      dockerfile: ./docker-files/app/app.Dockerfile
    restart: always
    ports:
      - 3000:3000
  redis-db:
    build:
      context: .
      target: production
      dockerfile: ./docker-files/app/redis.Dockerfile
    restart: always
    ports:
      - 6379:6379